version: "3.4"
services:
  broker:
    image: redis:6.0
    restart: always

  db:
    image: postgres:13
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: jonaswinkler/paperless-ng:0.9.11
    restart: always
    depends_on:
      - db
      - broker
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /Volumes/Paperless/export:/usr/src/paperless/export
      - /Volumes/Paperless/consume:/usr/src/paperless/consume
      - /Volumes/Paperless/data:/usr/src/paperless/data
      - /Volumes/Paperless/media:/usr/src/paperless/media
      #- data:/usr/src/paperless/data
      #- media:/usr/src/paperless/media
      #- ./consume:/usr/src/paperless/consume
      #- ./export:/usr/src/paperless/export
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db


volumes:
  pgdata:
  #data:
  #media:
